name: Deploy to GitHub Pages

on:
  # Триггер на push в ветку main
  push:
    branches: [ main ]
  # Также можно запускать вручную
  workflow_dispatch:

# Разрешаем джобе записывать файлы в репо (для gh-pages)
permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Устанавливаем Node.js
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Укажи версию, которую используешь
          cache: 'npm'

      # Устанавливаем зависимости
      - name: Install Dependencies
        run: npm ci

      # Собираем проект (используя base из vite.config.js)
      - name: Build
        run: npm run build

      # Пушим папку dist в ветку gh-pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages # Ветка, в которую будут помещены файлы билда